### ISSUE TITLE
Response to the server guy

### ISSUE THREAD

**Issue by kasparpalgi** [crewnew/stat-ee#3]
Casual, I don't understand. See if you can understand anything or can say something: https://chatgpt.com/share/b3601169-d80d-46c6-a7e5-1f02a0a70c50

**Comment by eapCJ** [comment]
I will take in consideration only **(1) create and configure the necessary servers and applications (as systemd services)**. Event though I have no idea what this implies and what I have to accomplish, it's much better than (Docker Kubernetes + Helm Charts) & Zero-trust, which are just keywords I've heard on the internet, zero knowledge about them.

**Comment by eapCJ** [comment]
Re-read, spend some time reading about it, why this is our job? We are not supposed to handle this. 

Can't and won't do it.

Redirect it to the "server guy".
