### ISSUE TITLE
Check if logic from DB queries are correct

### ISSUE THREAD

**Issue by kasparpalgi** [crewnew/stat-ee#4]
In this repository.ts file, it seems that you select by cluster (klaster) from the monthly data (kuised) table instead of by company registration code as it shall be. And the monthly normalization table queries I can't see.

**Comment by eapCJ** [comment]
>it seems that you select by cluster (klaster) from the monthly data (kuised) table instead of by company registration code as it shall be. 

✅ - Great, now I know how to query this.

>And the monthly normalization table queries I can't see.

❌ -  I assume he's refering to the tables `elujoulisuseindeks.norm_kuu_sds` & `elujoulisuseindeks.norm_kuu_kesk`,
for certain I have no idea what to do with the data from them.  Please tell me more.

**Comment by eapCJ** [comment]
I presume "kood" == "jykood", as in the table `kuised there is no row called `jykood` as there is in `aastased`.

**Comment by kasparpalgi** [comment]
Hans: You need to handle this data in the same way as with 'aastased' annual models: subtract the mean (tops) and divide by the standard deviation. In the provided SQL, there are also tables with feature names. Once normalized (subtracting the mean and dividing), transform it into a 12x3 data structure, transpose it, and feed it into the model.

Kaspar: Do we have at the moment data for every JSON property we return? If yes then we need I assume new JSON property names to return that new data?

Anyway, I said already to Hans that "I think we already have data to return for all JSON properties"

Hans: I think you named the monthly models compGrowth or something like that. But the output follows the same logic as in the annual models: 0 = low, 1 = medium, and 2 = high. You might have labeled them as 0 = x, 1 = y, and 2 = z.

&(/%€&#%"€%€&%/&(Ä (or how do you express swearing in github community)

**Comment by kasparpalgi** [comment]
Hans:
kasvu_k4_1
	
kasvu_k4_2

kasvu_k4_3

kasvu_k4_4

Kaspar: I guess these models must be used?

**Comment by eapCJ** [comment]
>In the documentation you can just add into the brackets explanation eg:
"modelY1: Represents the X dimension of the prediction (predicted probability of low vitality)." etc

It's already in the `Readme.md`. 

![Screenshot 2024-07-03 at 17 54 02](https://github.com/crewnew/stat-ee/assets/30572988/c830f755-3f90-428c-8d5d-c09ebad143cc)

**Comment by eapCJ** [comment]
> Kaspar: &(/%€&#%"€%€&%/&(Ä (or how do you express swearing in github community)

Pretty accurate.

**Comment by eapCJ** [comment]
> Hans: You need to handle this data in the same way as with 'aastased' annual models: subtract the mean (tops) and divide by the standard deviation. In the provided SQL, there are also tables with feature names. Once normalized (subtracting the mean and dividing), transform it into a 12x3 data structure, transpose it, and feed it into the model.

Kaspar: Do we have at the moment data for every JSON property we return? If yes then we need I assume new JSON property names to return that new data?

Anyway, I said already to Hans that "I think we already have data to return for all JSON properties"

Hans: I think you named the monthly models compGrowth or something like that. But the output follows the same logic as in the annual models: 0 = low, 1 = medium, and 2 = high. You might have labeled them as 0 = x, 1 = y, and 2 = z.

Kaspar: &(/%€&#%"€%€&%/&(Ä (or how do you express swearing in github community)


What does this mean, I have to create a new route that will handle “monthly”? 
Or I see I’m using a semi-related table called “kuised” when doing the “5th model”, should I substract&divide the values there? Or make a new route? But then, how does this work? 
This is new information.


```typescript
async predictIndicator(
    yearly: Yearly,
    indicator: ModelIndicator
  ): Promise<Prediction> {
    if (indicator === ModelIndicator.Growth) {
      return this.predictGrowthIndicator(yearly);
    }
   ....
)
```

**Comment by eapCJ** [comment]
I think I know what he meant, the above commit should resolve this issue.

**Comment by kasparpalgi** [comment]
KUISED (monthly) data that goes to front unchanged:

MAPPING!!:
  "EmppSect": 0.14, - protsentiil_sektor
  "Emp_n_Sect": 2312, - sektor_n
  "EmppSize": 0.15, - protsentiil_suurusgrupp
  "Emp_n_Size": 4516, - suurusgrupp_n
  "EmppCount": 0.14, - protsentiil_vald
  "Emp_n_Count": 2312 - vald_n

**Comment by kasparpalgi** [comment]
![image](https://github.com/crewnew/stat-ee/assets/71261121/d46b86e6-ac74-4f98-b077-551652d48669)

**Comment by kasparpalgi** [comment]
> KUISED (monthly) data that goes to front unchanged:
> 
> MAPPING!!: "EmppSect": 0.14, - protsentiil_sektor "Emp_n_Sect": 2312, - sektor_n "EmppSize": 0.15, - protsentiil_suurusgrupp "Emp_n_Size": 4516, - suurusgrupp_n "EmppCount": 0.14, - protsentiil_vald "Emp_n_Count": 2312 - vald_n

So these fields from AASTASED go to front unchanged and fields starting from 'kmd_m_min12' till 'tor_m_min1' go to normalisation and models before returning to the front.

**Comment by eapCJ** [comment]
![345838527-ad08973e-e9fc-492d-8eca-dcd574cc3616](https://github.com/crewnew/stat-ee/assets/30572988/78ed0a12-eef3-4f1c-aa9c-323df6c0b582)

I like talking in diagrams.

**Comment by eapCJ** [comment]
> > KUISED (monthly) data that goes to front unchanged:
> > MAPPING!!: "EmppSect": 0.14, - protsentiil_sektor "Emp_n_Sect": 2312, - sektor_n "EmppSize": 0.15, - protsentiil_suurusgrupp "Emp_n_Size": 4516, - suurusgrupp_n "EmppCount": 0.14, - protsentiil_vald "Emp_n_Count": 2312 - vald_n
> 
> So these fields from AASTASED go to front unchanged and fields starting from 'kmd_m_min12' till 'tor_m_min1' go to normalisation and models before returning to the front.

That should be about ... 100% correct.

**Comment by eapCJ** [comment]
> ![345838527-ad08973e-e9fc-492d-8eca-dcd574cc3616](https://private-user-images.githubusercontent.com/30572988/345847979-7e328470-28b0-426a-993e-05bfc8aa7d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDA4NzUsIm5iZiI6MTcyMDEwMDU3NSwicGF0aCI6Ii8zMDU3Mjk4OC8zNDU4NDc5NzktN2UzMjg0NzAtMjhiMC00MjZhLTk5M2UtMDViZmM4YWE3ZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEzNDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YmI5ZWU0ODk3YzA3MmY4MmUyZmRiODlmMGIzZGMxMzYyZGY5OWZmODMyM2NkMjEyMDYzYzZmMjE1MmY1MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2sOSvTWQFrpkz-oIdLiow0AE2V41Eq9y0sRVeftdkl4)
> 
> I like talking in diagrams.

As talked on the phone, I've understood correctly what does "green"/"red" (predictions,unchaged data) means and how they work. Will make soon a PR and close this.

**Comment by eapCJ** [comment]
[Whimsical Diagram](https://whimsical.com/ADW5WaEKjMq8qXeHTadCSe)

![Screenshot 2024-07-04 at 21 32 41](https://github.com/crewnew/stat-ee/assets/30572988/87de4d7a-95db-4d23-b5b1-341eef68f149)
![Screenshot 2024-07-04 at 20 53 31](https://github.com/crewnew/stat-ee/assets/30572988/fbdacc71-b65d-4223-a31e-2e85766cc38d)
![Screenshot 2024-07-04 at 20 53 27](https://github.com/crewnew/stat-ee/assets/30572988/c2ca3076-8014-489d-bdc1-bdda3ab5686d)

**Comment by eapCJ** [comment]
![Screenshot 2024-07-04 at 21 34 56](https://github.com/crewnew/stat-ee/assets/30572988/df42fe27-f7aa-4eb7-98db-b83b47af9d66)
![Screenshot 2024-07-04 at 21 34 52](https://github.com/crewnew/stat-ee/assets/30572988/0de6d147-2b8a-40a6-93d5-23ad15725bbd)
